{"name": "Авторизация курьера с несуществующими данными УЗ - получено сообщение об ошибке", "status": "passed", "start": 1719935531122, "stop": 1719935531219, "uuid": "227348d8-de8c-43b5-bd74-d07bbc69bf1e", "historyId": "5189935af01e9ed6e3e11e972d52be5f", "testCaseId": "5189935af01e9ed6e3e11e972d52be5f", "fullName": "tests.test_courier.TestLoginCourier#test_authorization_non_existent_courier_authorization_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "MacBook-Air-Vladislav.local"}, {"name": "thread", "value": "87558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}